/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
//NEW
import java.awt.TextField;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author WAHYU LINTANG
 */
public class AdTambahManajerProyek extends javax.swing.JFrame {

    /**
     * Creates new form MENU11
     */
    public AdTambahManajerProyek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbJenisKelaminMP = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textNamaMP = new java.awt.TextField();
        textTeleponMP = new java.awt.TextField();
        textAlamatMP = new java.awt.TextField();
        textIdMP = new java.awt.TextField();
        textPassMP = new java.awt.TextField();
        btnSimpan = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnLogout = new javax.swing.JButton();
        lblUserAdmin = new javax.swing.JLabel();
        btnTambahMP = new javax.swing.JButton();
        btnTambahPro = new javax.swing.JButton();
        btnHapusMP = new javax.swing.JButton();
        btnHapusPro = new javax.swing.JButton();
        btnBeranda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbJenisKelaminMP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jPanel1.add(cbJenisKelaminMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 289, -1, -1));

        jLabel1.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Manajer Proyek");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 32, 216, 72));

        jLabel14.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel14.setText("INPUT NAMA   :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 115, -1, -1));

        jLabel15.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel15.setText("INPUT  JENIS KELAMIN   :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 289, -1, -1));

        jLabel16.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel16.setText("INPUT  TELEPON   :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel17.setText("INPUT  ALAMAT   :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 186, -1, -1));

        jLabel18.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel18.setText("INPUT  ID   :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 222, -1, -1));

        jLabel19.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel19.setText("INPUT  PASSWORD   :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 258, -1, -1));
        jPanel1.add(textNamaMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 115, 229, -1));
        jPanel1.add(textTeleponMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 229, -1));
        jPanel1.add(textAlamatMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 186, 229, -1));
        jPanel1.add(textIdMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 222, 229, -1));
        jPanel1.add(textPassMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 258, 229, -1));

        btnSimpan.setText("SIMPAN");
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 379, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 204));

        btnLogout.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
        btnLogout.setText("LOGOUT ");

        lblUserAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserAdmin.setText("USER :  ADMIN");

        btnTambahMP.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnTambahMP.setText("TAMBAH MANAJER PROYEK");

        btnTambahPro.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnTambahPro.setText("TAMBAH PROGRAMMER");

        btnHapusMP.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnHapusMP.setText("HAPUS MANAJER PROYEK");

        btnHapusPro.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnHapusPro.setText("HAPUS PROGRAMMER");

        btnBeranda.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnBeranda.setText("BERANDA");

        jDesktopPane1.setLayer(btnLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblUserAdmin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnTambahMP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnTambahPro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnHapusMP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnHapusPro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBeranda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUserAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btnTambahPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHapusMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHapusPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahMP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusMP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Tubes PBO\\wallhaven-41419.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnHapusMP;
    private javax.swing.JButton btnHapusPro;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahMP;
    private javax.swing.JButton btnTambahPro;
    private javax.swing.JComboBox<String> cbJenisKelaminMP;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUserAdmin;
    private java.awt.TextField textAlamatMP;
    private java.awt.TextField textIdMP;
    private java.awt.TextField textNamaMP;
    private java.awt.TextField textPassMP;
    private java.awt.TextField textTeleponMP;
    // End of variables declaration//GEN-END:variables

    public void setlblUserAdmin(String input) {
        lblUserAdmin.setText(input);
    }

    public JButton getBtnBeranda() {
        return btnBeranda;
    }

    public JButton getBtnHapusMP() {
        return btnHapusMP;
    }

    public JButton getBtnHapusPro() {
        return btnHapusPro;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public JButton getBtnTambahMP() {
        return btnTambahMP;
    }

    public JButton getBtnTambahPro() {
        return btnTambahPro;
    }

    public int getCbJenisKelaminMP() {
        return cbJenisKelaminMP.getSelectedIndex();
    }

    public JLabel getLblUserAdmin() {
        return lblUserAdmin;
    }

    public String getTextAlamatMP() {
        return textAlamatMP.getText();
    }

    public String getTextIdMP() {
        return textIdMP.getText();
    }

    public String getTextNamaMP() {
        return textNamaMP.getText();
    }

    public String getTextPassMP() {
        return textPassMP.getText();
    }

    public String getTextTeleponMP() {
        return textTeleponMP.getText();
    }

    public void reset() {
        textAlamatMP.setText("");
        textIdMP.setText("");
        textNamaMP.setText("");
        textPassMP.setText("");
        textTeleponMP.setText("");
        cbJenisKelaminMP.setSelectedIndex(0);
    }

    public void viewErrorMsg(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public void addListener(ActionListener e) {
        btnBeranda.addActionListener(e);
        btnHapusMP.addActionListener(e);
        btnHapusPro.addActionListener(e);
        btnLogout.addActionListener(e);
        btnTambahMP.addActionListener(e);
        btnTambahPro.addActionListener(e);
        btnSimpan.addActionListener(e);
    }
}
