/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
//NEW
import java.awt.TextField;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author WAHYU LINTANG
 */
public class DetailProyekMP extends javax.swing.JFrame {

    /**
     * Creates new form MENU23
     */
    public DetailProyekMP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnLogout = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnTambahProyek = new javax.swing.JButton();
        btnHapusProyek = new javax.swing.JButton();
        btnDetailProyek = new javax.swing.JButton();
        btnBeranda = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbNamaProyek = new javax.swing.JComboBox<>();
        panel = new javax.swing.JTabbedPane();
        kelolaTugas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtNamaTugas = new java.awt.TextField();
        btnSimpanTgs = new javax.swing.JButton();
        panelTblTugas = new javax.swing.JScrollPane();
        tblTugas = new javax.swing.JTable();
        btnHapusTugas = new javax.swing.JButton();
        cbNamaTugas = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        kelolaPelaksana = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cbNamaProTP = new javax.swing.JComboBox<>();
        btnSimpanPelaksana = new javax.swing.JButton();
        btnHapusPelaksana = new javax.swing.JButton();
        cbNamaProHapus = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProDlmProyek = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProTersedia = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        setPelaksana = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbTugasSetP = new javax.swing.JComboBox<>();
        btnSimpanSetP = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbNamaProSP = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTugasSP = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblProSP = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblProyekAktif = new javax.swing.JLabel();
        btnAktifkan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konfigurasi Proyek");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 18, 179, 72));

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 204));

        btnLogout.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
        btnLogout.setText("LOGOUT ");

        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("USER :  MANAJER PROYEK");

        btnTambahProyek.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnTambahProyek.setText("TAMBAH PROYEK");

        btnHapusProyek.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnHapusProyek.setText("HAPUS PROYEK");

        btnDetailProyek.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnDetailProyek.setText("DETAIL PROYEK");

        btnBeranda.setFont(new java.awt.Font("Vani", 0, 10)); // NOI18N
        btnBeranda.setText("BERANDA");

        jDesktopPane1.setLayer(btnLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnTambahProyek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnHapusProyek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnDetailProyek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBeranda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
            .addComponent(btnBeranda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTambahProyek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHapusProyek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDetailProyek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnTambahProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnHapusProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnDetailProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 0, -1, 662));

        jLabel15.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel15.setText("INPUT  NAMA PROYEK   :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 102, -1, -1));

        jPanel1.add(cbNamaProyek, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 102, 173, -1));

        panel.setBackground(new java.awt.Color(0, 153, 204));

        kelolaTugas.setBackground(new java.awt.Color(0, 153, 204));

        jLabel14.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel14.setText("INPUT NAMA TUGAS   :");

        btnSimpanTgs.setText("SIMPAN");

        tblTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Pelaksana", "Status"
            }
        ));
        panelTblTugas.setViewportView(tblTugas);

        btnHapusTugas.setText("HAPUS");

        jLabel21.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel21.setText("Hapus Tugas               :");

        javax.swing.GroupLayout kelolaTugasLayout = new javax.swing.GroupLayout(kelolaTugas);
        kelolaTugas.setLayout(kelolaTugasLayout);
        kelolaTugasLayout.setHorizontalGroup(
            kelolaTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelolaTugasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(kelolaTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTblTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kelolaTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(kelolaTugasLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(25, 25, 25)
                            .addComponent(txtNamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnSimpanTgs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kelolaTugasLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kelolaTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kelolaTugasLayout.createSequentialGroup()
                                    .addGap(121, 121, 121)
                                    .addComponent(btnHapusTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbNamaTugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        kelolaTugasLayout.setVerticalGroup(
            kelolaTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelolaTugasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(kelolaTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtNamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btnSimpanTgs)
                .addGap(18, 18, 18)
                .addGroup(kelolaTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(5, 5, 5)
                .addComponent(btnHapusTugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTblTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel.addTab("Kelola Tugas", kelolaTugas);

        kelolaPelaksana.setBackground(new java.awt.Color(0, 153, 204));

        jLabel16.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel16.setText("INPUT NAMA PROGRAMMER   :");

        btnSimpanPelaksana.setText("SIMPAN");

        btnHapusPelaksana.setText("HAPUS");

        jLabel19.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel19.setText("Programmer Tersedia");

        tblProDlmProyek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "ID", "Jumlah Proyek"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProDlmProyek);

        tblProTersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "ID", "Jumlah Proyek"
            }
        ));
        jScrollPane2.setViewportView(tblProTersedia);

        jLabel20.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel20.setText("Hapus Programmer                   :");

        jLabel22.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel22.setText("Programmer dalam Proyek");

        javax.swing.GroupLayout kelolaPelaksanaLayout = new javax.swing.GroupLayout(kelolaPelaksana);
        kelolaPelaksana.setLayout(kelolaPelaksanaLayout);
        kelolaPelaksanaLayout.setHorizontalGroup(
            kelolaPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kelolaPelaksanaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(kelolaPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(kelolaPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(kelolaPelaksanaLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(25, 25, 25)
                            .addComponent(cbNamaProHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnHapusPelaksana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kelolaPelaksanaLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(25, 25, 25)
                            .addComponent(cbNamaProTP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSimpanPelaksana))
                        .addComponent(jLabel19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        kelolaPelaksanaLayout.setVerticalGroup(
            kelolaPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelolaPelaksanaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(kelolaPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbNamaProTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpanPelaksana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(kelolaPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNamaProHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusPelaksana)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panel.addTab("Kelola Pelaksana", kelolaPelaksana);

        setPelaksana.setBackground(new java.awt.Color(0, 153, 204));

        jLabel17.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel17.setText("INPUT NAMA TUGAS                :");

        btnSimpanSetP.setText("SIMPAN");

        jLabel18.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel18.setText("INPUT NAMA PROGRAMMER   :");

        tblTugasSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Pelaksana", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTugasSP);

        tblProSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "ID", "JumlahProyek"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblProSP);

        jLabel3.setText("Daftar Tugas");

        jLabel4.setText("Daftar Programmer dalam Proyek");

        javax.swing.GroupLayout setPelaksanaLayout = new javax.swing.GroupLayout(setPelaksana);
        setPelaksana.setLayout(setPelaksanaLayout);
        setPelaksanaLayout.setHorizontalGroup(
            setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPelaksanaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbNamaProSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTugasSetP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpanSetP, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setPelaksanaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        setPelaksanaLayout.setVerticalGroup(
            setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPelaksanaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbTugasSetP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setPelaksanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbNamaProSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpanSetP)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        panel.addTab("SET PELAKSANA", setPelaksana);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 486, 471));

        jLabel2.setText("Proyek Aktif");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 139, -1, -1));

        lblProyekAktif.setText("Tidak ada");
        jPanel1.add(lblProyekAktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 139, -1, -1));

        btnAktifkan.setText("Aktifkan");
        jPanel1.add(btnAktifkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 101, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Tubes PBO\\wallhaven-41419.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktifkan;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnDetailProyek;
    private javax.swing.JButton btnHapusPelaksana;
    private javax.swing.JButton btnHapusProyek;
    private javax.swing.JButton btnHapusTugas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSimpanPelaksana;
    private javax.swing.JButton btnSimpanSetP;
    private javax.swing.JButton btnSimpanTgs;
    private javax.swing.JButton btnTambahProyek;
    private javax.swing.JComboBox<String> cbNamaProHapus;
    private javax.swing.JComboBox<String> cbNamaProSP;
    private javax.swing.JComboBox<String> cbNamaProTP;
    private javax.swing.JComboBox<String> cbNamaProyek;
    private javax.swing.JComboBox<String> cbNamaTugas;
    private javax.swing.JComboBox<String> cbTugasSetP;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel kelolaPelaksana;
    private javax.swing.JPanel kelolaTugas;
    private javax.swing.JLabel lblProyekAktif;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JScrollPane panelTblTugas;
    private javax.swing.JPanel setPelaksana;
    private javax.swing.JTable tblProDlmProyek;
    private javax.swing.JTable tblProSP;
    private javax.swing.JTable tblProTersedia;
    private javax.swing.JTable tblTugas;
    private javax.swing.JTable tblTugasSP;
    private java.awt.TextField txtNamaTugas;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBeranda() {
        return btnBeranda;
    }

    public JButton getBtnDetailProyek() {
        return btnDetailProyek;
    }

    public JButton getBtnHapusPelaksana() {
        return btnHapusPelaksana;
    }

    public JButton getBtnHapusProyek() {
        return btnHapusProyek;
    }

    public JButton getBtnAktifkan() {
        return btnAktifkan;
    }

    public void setLblProyekAktif(String input) {
        lblProyekAktif.setText(input);
    }

    public JTable getTblTugas() {
        return tblTugas;
    }

    public JButton getBtnHapusTugas() {
        return btnHapusTugas;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnSimpanPelaksana() {
        return btnSimpanPelaksana;
    }

    public JButton getBtnSimpanSetP() {
        return btnSimpanSetP;
    }

    public JButton getBtnSimpanTgs() {
        return btnSimpanTgs;
    }

    public JButton getBtnTambahProyek() {
        return btnTambahProyek;
    }

    public int getCbNamaProHapus() {
        return cbNamaProHapus.getSelectedIndex();
    }

    public void setCbNamaProyek(String input) {
        cbNamaProyek.addItem(input);
    }

    public void setCbTugasSetP(String input) {
        cbTugasSetP.addItem(input);
    }

    public void setCbNamaProSP(String input) {
        cbNamaProSP.addItem(input);
    }

    

    public void setCbNamaTugas(String input) {
        cbNamaTugas.addItem(input);
    }
    
     public void resetCbTugasSetP() {
        cbTugasSetP.removeAllItems();
    }
     
     public void resetCbNamaProSP(){
         cbNamaProSP.removeAllItems();
     }

    public void resetCbNamaTugas() {
        cbNamaTugas.removeAllItems();
    }

    public void resetCbNamaProyek() {
        cbNamaProyek.removeAllItems();
    }

    public void resetCbNamaProTP() {
        cbNamaProTP.removeAllItems();
    }

    public void resetCbNamaProHapus() {
        cbNamaProHapus.removeAllItems();
    }

    public void reset() {
        resetCbNamaProHapus();
        resetCbNamaProTP();
        resetCbNamaProyek();
        resetCbNamaTugas();
        resetCbNamaProSP();
        resetCbTugasSetP();
    }

    public void setCbNamaProTP(String e) {
        cbNamaProTP.addItem(e);
    }

    public void setCbNamaProHapus(String e) {
        cbNamaProHapus.addItem(e);
    }

    public void setLblUser(String input) {
        lblUser.setText(input);
    }

    public int getCbNamaProSP() {
        return cbNamaProSP.getSelectedIndex();
    }

    public int getCbNamaProTP() {
        return cbNamaProTP.getSelectedIndex();
    }

    public int getCbNamaProyek() {
        return cbNamaProyek.getSelectedIndex();
    }

    public int getCbNamaTugas() {
        return cbNamaTugas.getSelectedIndex();
    }

    public int getCbTugasSetP() {
        return cbTugasSetP.getSelectedIndex();
    }

    public JScrollPane getPanelTblTugas() {
        return panelTblTugas;
    }

    public void addListener(ActionListener e) {
        btnBeranda.addActionListener(e);
        btnDetailProyek.addActionListener(e);
        btnHapusProyek.addActionListener(e);
        btnLogout.addActionListener(e);
        btnTambahProyek.addActionListener(e);
        btnAktifkan.addActionListener(e);
        btnHapusPelaksana.addActionListener(e);
        btnSimpanPelaksana.addActionListener(e);
        btnSimpanSetP.addActionListener(e);
        btnSimpanTgs.addActionListener(e);
        btnHapusTugas.addActionListener(e);
        btnSimpanSetP.addActionListener(e);
    }

    public JTabbedPane getPanel() {
        return panel;
    }

    public void viewErrorMsg(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public String getTxtNamaTugas() {
        return txtNamaTugas.getText();
    }

    public void setTxtNamaTugas(String s) {
        txtNamaTugas.setText(s);
    }

    public JTable getTblProDlmProyek() {
        return tblProDlmProyek;
    }

    public JTable getTblProTersedia() {
        return tblProTersedia;
    }

    public JTable getTblTugasSP() {
        return tblTugasSP;
    }

    public JTable getTblProSP() {
        return tblProSP;
    }

}
